on: [push]

name: Update Okteto Container

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: ${{ secrets.OKTETO_NAMESPACE }}
    
    - name: "Trigger the Pipeline"
      uses: okteto/pipeline@latest
      with:
        name: ${{ secrets.OKTETO_APP_NAME }}
