on:
  push:
  workflow_dispatch:

name: Update Heroku Container

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      name: Checkout
    
    - uses: akhileshns/heroku-deploy@v3.12.12
      name: Deploy to Heroku
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true
      env:
        HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
        HD_PORT: ${{secrets.PORT}}
        HD_URL_BASE: ${{secrets.URL_BASE}}
